# Generated by Django 2.2.6 on 2019-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
    ]
