# Generated by Django 2.2.6 on 2019-10-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='update_date',
        ),
    ]
