# Generated by Django 2.2.6 on 2019-10-26 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='create_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
